name: 'Full CICD Process'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      TF_API_TOKEN:
        required: true

jobs:
  # you cannot pass env vars directly to the input of a workflow call
  # hence giving them as job outputs as a workaround
  setup-constant-variables:
    name: "Set Up CICD Parameters"
    runs-on: ubuntu-latest
    outputs:
      node-version: 18.x
      yarn-version: 1.22.19
    steps:
    # This placeholder step is required to create a valid job
    - name: Initialisation
      run: echo "Beginning CICD..." 

  run-tests-and-format-code:
    name: "Run Automated Tests and Check Code Format"
    needs: setup-constant-variables
    uses: ./.github/workflows/run_tests_and_format_code.yml
    with:
      node-version: ${{ needs.setup-constant-variables.outputs.node-version }}
      yarn-version: ${{ needs.setup-constant-variables.outputs.yarn-version }}

  deploy-infrastructure:
    name: 'Deploy Infrastructure'
    needs: run-tests-and-format-code
    uses: ./.github/workflows/deploy_infra.yml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  deploy-web-app:
    name: Deploy Web Application
    needs: deploy-infrastructure
    uses: ./.github/workflows/deploy_web_app.yml
    with:
      environment: ${{ inputs.environment }}
      node-version: ${{ needs.setup-constant-variables.outputs.node-version }}
      yarn-version: ${{ needs.setup-constant-variables.outputs.yarn-version }}