name: 'CICD - Feature Deployment'

on:
  push:

jobs:
  feature-deployment:
    name: "Run Automated Tests and Check Code Format"
    uses: ./.github/workflows/cicd--generic.yml
    with:
      environment: development
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}