name: 'Test and Deploy Web-App'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      node-version:
        required: true
        type: string
      yarn-version:
        required: true
        type: string  

env:
  AWS_REGION: eu-west-1

# Required to use GitHub OIDC Token with AWS
permissions:
  id-token: write

jobs:
  deploy-web-app:
    name: 'Deploy Web App'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Checkout Git Repo
      uses: actions/checkout@v3

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.yarn-version }}
      
    - name: Install Yarn
      run: npm install --global yarn@${{ inputs.yarn-version }}

    - name: Install Project Dependencies
      run: yarn install

    - name: Build SPA Project
      run: yarn build:${{ inputs.environment }}

    - name: Login to AWS with DEV credentials
      if: ${{ inputs.environment == 'development'}}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::646359775865:role/RoleForGithubActions
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to AWS with PROD credentials
      if: ${{ inputs.environment == 'production'}}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::787939685470:role/RoleForGithubActions
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy Static Assets into S3 Bucket
      run: |
        set -o pipefail
        SSM_PARAM_NAME=/smalldomains/web-app/s3-deployment

        S3_DEPLOY_NAME=$(aws ssm get-parameter --name $SSM_PARAM_NAME --with-decryption | jq -r .Parameter.Value)
        aws s3 sync ./build s3://${S3_DEPLOY_NAME}