name: 'Deploy Terraform Infrastructure'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      TF_API_TOKEN:
        required: true

jobs:
  deploy-infrastructure:
    name: 'Deploy Infrastructure'
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
    - name: Select Terraform WorkSpace
      run: |
          case ${{ inputs.environment }} in
            development)  echo "TF_WORKSPACE=smalldomains--web-app-dev" >> $GITHUB_ENV;;
            production)   echo "TF_WORKSPACE=smalldomains--web-app-prod" >> $GITHUB_ENV;;
            *)            echo "${{ inputs.environment }} is an unrecognised environment"; exit 1;;
          esac
    
    - name: View Environment Variables
      run: echo "Using TF_WORKSPACE of $TF_WORKSPACE"

    - name: Checkout Git Repo
      uses: actions/checkout@v3
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      working-directory: ./.terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: ./.terraform
      run: terraform plan

    - name: Terraform Apply
      working-directory: ./.terraform
      run: terraform apply -auto-approve
