name: 'Check Code Format and Run Automated Tests'

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      yarn-version:
        required: true
        type: string  

jobs:
  check-terraform-code:
    name: 'Check Terraform Code'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git Repo
      uses: action/checkout@v3
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      working-directory: ./.terraform
      run: terraform init

    - name: Terraform Format
      working-directory: ./.terraform
      run: terraform fmt -check

    - name: Terraform Validate
      working-directory: ./.terraform
      run: terraform validate

  run-react-unit-tests:
    name: 'Run Unit Tests on React App'

    steps:
    - name: Checkout Git Repo
      uses: action/checkout@v3

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
      
    - name: Install Yarn
      run: npm install --global yarn@${{ inputs.yarn-version }}

    - name: Run Unit Tests
      run: yarn test --all --watchAll=false
