name: 'Check Code Format and Run Automated Tests'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      node-version:
        required: true
        type: string
      yarn-version:
        required: true
        type: string  
    secrets:
      TF_API_TOKEN:
        required: true

jobs:
  check-terraform-code:
    name: 'Check Terraform Code'
    runs-on: ubuntu-latest

    steps:
    - name: Set Environment Variables
      run: |
        case ${{ inputs.environment }} in
          development)  echo "TF_WORKSPACE=smalldomains--web-app-dev" >> $GITHUB_ENV;;
          production)   echo "TF_WORKSPACE=smalldomains--web-app-prod" >> $GITHUB_ENV;;
          *)            echo "${{ inputs.environment }} is an unrecognised environment"; exit 1;;
        esac

    - name: View Environment Variables
      run: echo "Using TF_WORKSPACE of $TF_WORKSPACE"

    - name: Checkout Git Repo
      uses: actions/checkout@v3
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Format
      working-directory: terraform
      run: terraform fmt -check

    - name: Terraform Validate
      working-directory: terraform
      run: terraform validate

  run-react-unit-tests:
    name: 'Run Unit Tests on React App'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git Repo
      uses: actions/checkout@v3

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
      
    - name: Install Yarn
      run: npm install --global yarn@${{ inputs.yarn-version }}

    - name: Install Project Dependencies
      run: yarn install

    - name: Run Unit Tests
      run: yarn test --all --verbose --watchAll=false